export interface PortfolioProject {
  slug: string
  client: string
  url: string
  image: string
  category: "web" | "ecommerce" | "landing" | "app" | "ia"
  tags: string[]
  result?: string
  es: { desc: string }
  en: { desc: string }
}

export const PORTFOLIO: PortfolioProject[] = [
  // ── WEB DEVELOPMENT ─────────────────────────────────────────────────
  {
    slug: "alkemia",
    client: "ALKEMIA",
    url: "https://goalkemia.com",
    image: "/images/alkemia.png",
    category: "web",
    tags: ["Web", "Branding", "IA"],
    result: "Plataforma IA",
    es: { desc: "Diseño y desarrollo de la nueva plataforma digital para acompañar la evolución de marca en tecnología, automatización e IA." },
    en: { desc: "Design and development of a new digital platform accompanying brand evolution in technology, automation and AI." },
  },
  {
    slug: "fpnn",
    client: "Fundación Por Nuestros Niños",
    url: "http://fpnn.org.ar",
    image: "/images/fpnn.png",
    category: "web",
    tags: ["Web"],
    es: { desc: "Sitio completamente custom con diseño personalizado que refleja la misión, programas y formas de colaborar de la fundación." },
    en: { desc: "Fully custom site with personalized design reflecting the foundation's mission, programs and collaboration methods." },
  },
  {
    slug: "grupo-terra-lauquen",
    client: "Grupo Terra Lauquen",
    url: "https://grupoterralauquen.com.ar",
    image: "/images/grupoterralauquen.com.ar_.png",
    category: "web",
    tags: ["Web"],
    es: { desc: "Sitio corporativo para grupo empresarial con múltiples divisiones y presencia regional." },
    en: { desc: "Corporate site for business group with multiple divisions and regional presence." },
  },
  {
    slug: "cichic",
    client: "Cichic",
    url: "https://chichicwinerelax.com",
    image: "/images/chichicImage.png",
    category: "web",
    tags: ["Web", "E-commerce"],
    es: { desc: "Plataforma e-commerce de moda y accesorios con catálogo de productos, carrito de compras y pasarela de pago." },
    en: { desc: "Fashion and accessories e-commerce platform with product catalog, shopping cart and payment gateway." },
  },
  {
    slug: "tenis-de-mesa-trenque",
    client: "Tenis de Mesa Trenque",
    url: "https://tenisdemesatrenque.com.ar",
    image: "/images/tenisdemesatrenque.com.ar_.png",
    category: "web",
    tags: ["Web", "App"],
    result: "React App",
    es: { desc: "Sitio institucional para club deportivo desarrollado en React con sistema de torneos, inscripciones y resultados en tiempo real." },
    en: { desc: "Institutional site for sports club built in React with tournament system, registrations and real-time results." },
  },
  // ── ECOMMERCE ───────────────────────────────────────────────────────
  {
    slug: "greta-kids-atelier",
    client: "Greta Kids Atelier",
    url: "https://gretakidsatelier.com.ar",
    image: "/images/greta.png",
    category: "ecommerce",
    tags: ["E-commerce"],
    es: { desc: "Tienda de ropa infantil WooCommerce con catálogo de productos variables y sistema de gestión de inventario." },
    en: { desc: "WooCommerce children's clothing store with variable product catalog and inventory management." },
  },
  {
    slug: "alaux-neumaticos",
    client: "Alaux Neumáticos",
    url: "https://tiendaalaux.com.ar",
    image: "/images/alaux.png",
    category: "ecommerce",
    tags: ["E-commerce"],
    es: { desc: "Ecommerce de neumáticos con buscador por vehículo, 500+ productos y configuración de envíos regionales." },
    en: { desc: "Tire ecommerce with vehicle search, 500+ products and regional shipping configuration." },
  },
  {
    slug: "gangafan",
    client: "GangaFan",
    url: "https://gangafan.com",
    image: "/images/gangafan-page.png",
    category: "ecommerce",
    tags: ["E-commerce"],
    es: { desc: "Plataforma de ventas de merchandising con gestión de promociones, descuentos y pagos integrados." },
    en: { desc: "Merchandise sales platform with promotion management, discounts and integrated payments." },
  },
  {
    slug: "megamayorista",
    client: "Megamayorista",
    url: "https://megamayorista.com",
    image: "/images/megamayorista.png",
    category: "ecommerce",
    tags: ["E-commerce"],
    es: { desc: "Tienda mayorista con catálogo extenso y configuración de precios por volumen de compra." },
    en: { desc: "Wholesale store with extensive catalog and volume-based pricing configuration." },
  },
  {
    slug: "nutriac",
    client: "Nutriac",
    url: "https://nutriac.com.ar",
    image: "/images/nutriac.png",
    category: "ecommerce",
    tags: ["E-commerce"],
    result: "100% Custom",
    es: { desc: "Ecommerce WooCommerce 100% custom en PHP y SCSS integrado al sistema PICASSO para clientes registrados." },
    en: { desc: "100% custom WooCommerce ecommerce in PHP and SCSS integrated with the PICASSO system for registered clients." },
  },
  // ── LANDING PAGES ───────────────────────────────────────────────────
  {
    slug: "castro-yeso",
    client: "Castro Yeso",
    url: "https://castro-yeso.com",
    image: "/images/castroweb.png",
    category: "landing",
    tags: ["Web", "SEO"],
    result: "+3x leads",
    es: { desc: "Landing 100% personalizada en WordPress para empresa de yesería. Galería, servicios, formulario y CTAs estratégicas optimizados para SEO local." },
    en: { desc: "100% custom WordPress landing for plastering company. Gallery, services, contact form and strategic CTAs optimized for local SEO." },
  },
  {
    slug: "asesoria-dialogar",
    client: "Asesoría Dialogar",
    url: "https://asesoriadialogar.com.ar",
    image: "/images/dialogar.png",
    category: "landing",
    tags: ["Web", "SEO"],
    es: { desc: "Landing profesional en WordPress para asesoría contable y financiera, optimizada para generar confianza y convertir leads." },
    en: { desc: "Professional WordPress landing for accounting and financial advisory, optimized to build trust and generate leads." },
  },
  {
    slug: "starley",
    client: "Starley",
    url: "https://starley.com.ar",
    image: "/images/starleyweb.png",
    category: "landing",
    tags: ["Web"],
    es: { desc: "WordPress con Flatsome para catálogo de productos e información empresarial con mejoras personalizadas." },
    en: { desc: "WordPress with Flatsome theme for product catalog and company information with custom improvements." },
  },
  {
    slug: "jose-jose",
    client: "José José",
    url: "https://www.josejoseoficial.com.mx",
    image: "/images/josejose.png",
    category: "landing",
    tags: ["Web", "Branding"],
    result: "Lanzamiento",
    es: { desc: "Sitio en WordPress con tema completamente personalizado en PHP, MySQL, HTML5, SCSS y JavaScript, sin plantillas preexistentes." },
    en: { desc: "WordPress site with fully custom PHP, MySQL, HTML5, SCSS and JavaScript theme, no prebuilt templates." },
  },
  {
    slug: "protorneos",
    client: "Protorneos",
    url: "https://protorneos.com",
    image: "/images/protorneo.png",
    category: "landing",
    tags: ["Web", "App"],
    result: "1.2k usuarios",
    es: { desc: "Sitio estático liviano desarrollado con HTML5, CSS3 y JavaScript puro, optimizado para velocidad y fácil mantenimiento." },
    en: { desc: "Lightweight static site built with pure HTML5, CSS3 and JavaScript, optimized for speed and easy maintenance." },
  },
  // ── APPS & SYSTEMS ──────────────────────────────────────────────────
  {
    slug: "soy-lidia",
    client: "Soy LIDIA",
    url: "https://soylidia.com",
    image: "/images/soylidia.png",
    category: "app",
    tags: ["App", "IA"],
    result: "20+ clínicas",
    es: { desc: "Sistema de gestión para profesionales de la salud con WhatsApp integrado. Calendario, pacientes, equipo, sucursales y pagos." },
    en: { desc: "Management system for health professionals with integrated WhatsApp. Calendar, patients, team, branches and payments." },
  },
  {
    slug: "lidia-superadmin",
    client: "LIDIA Superadmin",
    url: "https://soylidia.com/superadmin",
    image: "/images/superadmin.png",
    category: "app",
    tags: ["App", "IA"],
    es: { desc: "Panel de administración del sistema LIDIA con gestión multi-sucursal, reportes y control completo de la plataforma." },
    en: { desc: "LIDIA system administration panel with multi-branch management, reports and full platform control." },
  },
  {
    slug: "talleres-unidos",
    client: "Club de Escritura",
    url: "https://club.rulodeviaje.com",
    image: "/images/talleres.png",
    category: "app",
    tags: ["App", "Web"],
    es: { desc: "Sistema web con login de usuarios, suscripción y desafíos mensuales de escritura y lectura para comunidades creativas." },
    en: { desc: "Web system with user login, subscriptions and monthly creative writing and reading challenges for communities." },
  },
  {
    slug: "tenis-ranking",
    client: "Ranking Tenis de Mesa",
    url: "https://tenisdemesatrenque.com.ar",
    image: "/images/tenisDeMesaImageRank.png",
    category: "app",
    tags: ["App", "Web"],
    es: { desc: "Sistema completo de gestión de ranking para Tenis de Mesa con perfiles de jugadores, estadísticas y clasificaciones." },
    en: { desc: "Complete ranking management system for Table Tennis with player profiles, statistics and classifications." },
  },
  // ── IA & CHATBOTS ───────────────────────────────────────────────────
  {
    slug: "zerxio",
    client: "Zerxio",
    url: "https://zerxio.com",
    image: "/images/zerxio.com.png",
    category: "ia",
    tags: ["IA", "Web"],
    es: { desc: "Plataforma tecnológica con integración de IA para automatización de procesos y atención al cliente inteligente." },
    en: { desc: "Technology platform with AI integration for process automation and intelligent customer service." },
  },
  {
    slug: "consultora-on",
    client: "Consultora ON",
    url: "#",
    image: "/images/consultoraon.png",
    category: "ia",
    tags: ["IA", "Automatización"],
    es: { desc: "Sistema de automatización e inteligencia artificial para procesos de consultoría y atención al cliente." },
    en: { desc: "Automation and artificial intelligence system for consulting processes and customer service." },
  },
]

export type ProjectCategory = "all" | "web" | "ecommerce" | "landing" | "app" | "ia"
